pais_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Pais:new" }

pais_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Pais:exportar" }
    
pais_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Pais:create" }
    requirements: { _method: post }

pais_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Pais:edit" }

pais_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Pais:update" }
    requirements: { _method: post|put }

pais_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Pais:delete" }
    requirements: { _method: post|delete }
pais:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Pais:index" , search: ''}
